targets:
  $default:
    builders:
      isar_community_generator:
        generate_for:
          - lib/core_new/**
      riverpod_generator:
        generate_for:
          - lib/features/**
          - lib/core_new/**
          - lib/shared/**
        
        
