targets:
  $default:
    builders:
      isar_community_generator:
        generate_for:
          - lib/features/**/model/**
          - lib/core/**
      riverpod_generator:
        generate_for:
          - lib/features/**/view_model/**
          - lib/shared/**
        
        
