import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:shonenx/features/discovery/presentation/widgets/episodes_panel/episode_list_panel.dart';
import 'package:shonenx/shared/models/app_theme_preset.dart';
import 'package:shonenx/shared/providers/theme_prefs_provider.dart';
import 'package:shonenx/shared/providers/ui_prefs_provider.dart';

// constraints:
// noise: 0.0 <-> 0.15

class BuiltInPresets {
  static final List<AppThemePreset> all = [
    AppThemePreset(
      id: '1',
      name: 'Default ShonenX',
      description: 'Warm golden accents with classic card styling.',
      author: '@roshancodespace',
      version: 1,
      previewColors: [0xFFFBBF24, 0xFFF59E0B, 0xFF78350F],
      themeMode: ThemeMode.system,
      flexScheme: FlexScheme.material,
      themeVariant: AppThemeVariant.classic,
      exclusiveScheme: 'golden_hour',
      blendLevel: 10,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.topGlow,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.primaryInfused,
      gradientIntensity: 0.5,
      useNoiseOverlay: true,
      noiseOpacity: 0.09,
      uiRoundness: 12.0,
      cardStyle: MediaCardStyle.expressive,
      continueWatchingStyle: ContinueWatchingStyle.wideBanner,
      continueReadingStyle: ContinueReadingStyle.wideBanner,
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '2',
      name: 'Frostbite',
      description: 'Icy boreal greens with frosted glass cards.',
      author: '@northpole',
      version: 1,
      previewColors: [0xFF34D399, 0xFF60A5FA, 0xFF065F46],
      themeMode: ThemeMode.dark,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.fidelity,
      exclusiveScheme: 'arctic_aurora',
      blendLevel: 20,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.topGlow,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.vibrantMix,
      gradientIntensity: 0.55,
      useNoiseOverlay: true,
      noiseOpacity: 0.06,
      uiRoundness: 14.0,
      cardStyle: MediaCardStyle.frosted,
      continueWatchingStyle: ContinueWatchingStyle.frosted,
      continueReadingStyle: ContinueReadingStyle.frosted,
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '3',
      name: 'Neon Pulse',
      description: 'Deep neon glow with cinematic, borderless cards.',
      author: '@tokyofuture',
      version: 1,
      previewColors: [0xFFB794F6, 0xFFFF6EC7, 0xFF0D0E15],
      themeMode: ThemeMode.dark,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.vibrant,
      exclusiveScheme: 'midnight_tokyo',
      useAmoled: true,
      blendLevel: 5,
      useGradients: false,
      uiRoundness: 10.0,
      cardStyle: MediaCardStyle.neon,
      continueWatchingStyle: ContinueWatchingStyle.neon,
      continueReadingStyle: ContinueReadingStyle.neon,
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '4',
      name: 'Sakura Dream',
      description: 'Cherry blossom pink palette with soft tonal seeding.',
      author: '@cherryblossom',
      version: 1,
      previewColors: [0xFFDB2777, 0xFFF472B6, 0xFFFAF3F5],
      themeMode: ThemeMode.light,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.tonalSpot,
      colorSeed: 0xFFDB2777,
      blendLevel: 15,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.linear,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.secondaryInfused,
      gradientIntensity: 0.35,
      uiRoundness: 20.0,
      cardStyle: MediaCardStyle.expressive,
      continueWatchingStyle: ContinueWatchingStyle.editorial,
      continueReadingStyle: ContinueReadingStyle.editorial,
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '5',
      name: 'animestream cheap copy',
      description: 'Minimal lime-accent theme with wide banner cards.',
      author: '@frostnova721',
      version: 1,
      previewColors: [0xFFCAF979, 0xFF2F3A13, 0xFF121212],
      themeMode: ThemeMode.dark,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.classic,
      exclusiveScheme: 'anime_stream',
      blendLevel: 0,
      useGradients: false,
      useNoiseOverlay: false,
      uiRoundness: 12.0,
      cardStyle: MediaCardStyle.wideBanner,
      continueWatchingStyle: ContinueWatchingStyle.wideBanner,
      continueReadingStyle: ContinueReadingStyle.wideBanner,
      episodeViewMode: EpisodeViewMode.classic,
      navBarStyle: NavBarStyle.minimal,
    ),
  ];
}
