import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:shonenx/features/discovery/presentation/widgets/episodes_panel/episode_list_panel.dart';
import 'package:shonenx/shared/models/app_theme_preset.dart';
import 'package:shonenx/shared/providers/theme_prefs_provider.dart';
import 'package:shonenx/shared/providers/ui_prefs_provider.dart';

// constraints:
// noise: 0.0 <-> 0.15

class BuiltInPresets {
  static final List<AppThemePreset> all = [
    AppThemePreset(
      id: '1',
      name: 'Blood',
      description:
          'Rich blood-red tones, dramatic contrast, and expressive wide content cards.',
      author: '@roshancodespace',
      version: 2,
      previewColors: [0xFF7e1e1e, 0xFF651616, 0xFF5e1616],
      themeMode: ThemeMode.system,
      flexScheme: FlexScheme.shadRed,
      themeVariant: AppThemeVariant.classic,
      blendLevel: 0,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.topGlow,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.primaryInfused,
      gradientIntensity: 0.65,
      useNoiseOverlay: true,
      noiseOpacity: 0.09,
      uiRoundness: 16.0,
      cardStyle: MediaCardStyle.expressive,
      continueWatchingStyle: ContinueWatchingStyle.expressive,
      continueReadingStyle: ContinueReadingStyle.expressive,
      cardStyleWideModes: const {
        "cw_expressive": true,
        "media_expressive": false,
        "cr_expressive": true,
      },
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '2',
      name: 'Frostbite',
      description: 'Icy boreal greens with frosted glass editorial cards.',
      author: '@northpole',
      version: 2,
      previewColors: [0xFF10B981, 0xFF06B6D4, 0xFF047857],
      themeMode: ThemeMode.dark,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.tonalSpot,
      colorSeed: 0xFF10B981,
      blendLevel: 16,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.linear,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.secondaryInfused,
      gradientIntensity: 0.35,
      useNoiseOverlay: false,
      uiRoundness: 18.0,
      cardStyle: MediaCardStyle.expressive,
      continueWatchingStyle: ContinueWatchingStyle.editorial,
      continueReadingStyle: ContinueReadingStyle.editorial,
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '3',
      name: 'Neon Pulse',
      description: 'Vivid neon glow with modern Material You styling.',
      author: '@tokyofuture',
      version: 2,
      previewColors: [0xFF8B5CF6, 0xFFEC4899, 0xFF090A0F],
      themeMode: ThemeMode.dark,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.vibrant,
      colorSeed: 0xFF8B5CF6,
      useAmoled: true,
      blendLevel: 12,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.radial,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.vibrantMix,
      gradientIntensity: 0.4,
      useNoiseOverlay: false,
      uiRoundness: 16.0,
      cardStyle: MediaCardStyle.material,
      continueWatchingStyle: ContinueWatchingStyle.material,
      continueReadingStyle: ContinueReadingStyle.material,
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '4',
      name: 'Sakura Dream',
      description: 'Cherry blossom pink palette with soft tonal seeding.',
      author: '@cherryblossom',
      version: 1,
      previewColors: [0xFFDB2777, 0xFFF472B6, 0xFFFAF3F5],
      themeMode: ThemeMode.light,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.tonalSpot,
      colorSeed: 0xFFDB2777,
      blendLevel: 15,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.linear,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.secondaryInfused,
      gradientIntensity: 0.35,
      uiRoundness: 20.0,
      cardStyle: MediaCardStyle.expressive,
      continueWatchingStyle: ContinueWatchingStyle.expressive,
      continueReadingStyle: ContinueReadingStyle.expressive,
      episodeViewMode: EpisodeViewMode.classic,
    ),
    AppThemePreset(
      id: '5',
      name: 'animestream Ultra',
      description: 'Sleek dark lime aesthetics with wide banner cards.',
      author: '@frostnova721',
      version: 2,
      previewColors: [0xFFA3E635, 0xFF3F6212, 0xFF111827],
      themeMode: ThemeMode.dark,
      flexScheme: FlexScheme.custom,
      themeVariant: AppThemeVariant.tonalSpot,
      colorSeed: 0xFFA3E635,
      blendLevel: 10,
      useGradients: true,
      gradientStyle: BackgroundGradientStyle.topGlow,
      gradientDirection: BackgroundGradientDirection.diagonalUp,
      gradientColorPair: BackgroundGradientColorPair.primaryInfused,
      gradientIntensity: 0.3,
      useNoiseOverlay: false,
      uiRoundness: 16.0,
      cardStyle: MediaCardStyle.wideBanner,
      continueWatchingStyle: ContinueWatchingStyle.wideBanner,
      continueReadingStyle: ContinueReadingStyle.wideBanner,
      episodeViewMode: EpisodeViewMode.classic,
      navBarStyle: NavBarStyle.minimal,
    ),
  ];
}
